# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3943d0689760153680331cca515b59e89dc00c8152ae502c7e19713ca3c49a8810ae713f06a7284b085820ed1c2d724aba777fdf5dc484449a7b2e31b9eb143

test:
  secret_key_base: 77fce37de29e4917ca58a6bd29def34608f95c0ca331ee920ec76ae85cfdd30cc63beca8bb2cb1d23acd914d5d189d00d0b478aa2ba77f74667d3d6bedff622c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
